### ISSUE TITLE
Custom HtmlFormatter

### ISSUE THREAD

**Issue by hkfuertes** [martijnversluis/ChordSheetJS#1151]
Hello I just want to extend the functionality to create a custom formatter... can I do that without monkey patching? Or should I create a pr? (maybe when I have this running I will).

I run (and made) this website (spanish catholic songbook, [doceacordes.es](https://doceacordes.es)) and I started with a hand made tables formatter, but a year ago I found a more "elegant" way of doing this.

```html
<!-- [c]esto es un[d]a pru[em]eba. -->
<div class="position-relative pt-3">
  <span class="lyric chord none" data-chord="C">esto </span>
  <span class="none"> es un </span>
  <span class="lyric chord none" data-chord="D">a </span>
  <span class="none"> pru </span>
  <span class="lyric chord none" data-chord="em">eba.</span>
  <br>
</div>
```
And the matching styles:
```css
.chorus { font-weight: bold; }
.lyric { line-height: 2.7; white-space: pre;  }

.chord {
  position: relative;
  display: inline-block;
}

.chord:before {
  content: attr(data-chord); /*<---- this is the key element!*/
  position: absolute;
  top: -1rem;
  color: #001f3f;
}
```

Again I was doing all the key changes and parsing and everyting myself, but I just came across this awesome library and I plan on using it. I already have a proof of concept preact component using this library and "my" formatter... but I wanted to follow your conventions and thats why I asked if I can do that or if I need to open a PR (wich eventually I think I will...)

I also posted my solution here for if it can help anyone or if any admin wants to make the formatter.
