### ISSUE TITLE
Help CSS

### ISSUE THREAD

**Issue by erzonmr** [martijnversluis/ChordSheetJS#1307]
Greetings to the creator of this library, greetings to those who pass by :-) 

Guys, I have a problem, I'm converting chord.pro files to HTML, but I don't know how to implement the CSS in my result, the resulting song looks messy ... can someone guide me...?

**Comment by soondor81** [comment]
@erzonmr 

This is a sheet music site I created using ChordSheetJS.
https://www.bomione.co.kr

When you use
```typescript
new ChordSheetJS.HtmlDivFormatter().format(song);
```
HTML is generated with classes applied according to the format. You can then assign appropriate styles to these classes.


#### Example
```css
.chord-sheet {
    font-family: Arial, sans-serif;
    font-size: 16px;
    line-height: 1.4;
}

.verse {
    padding: 12px;
    border-radius: 6px;
}

.chorus {
    padding: 12px;
    border-radius: 6px;
}

.bridge {
    padding: 12px;
    border-radius: 6px;
}

.row {
    display: flex;
    flex-wrap: wrap;
}

.column {
    flex: 0;
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    padding-left: 0!important;
    padding-right: 0!important;
}

.chord {
    font-size: 16px;
    text-align: left;
    font-weight: bold;
    white-space: nowrap;
    min-height: 1.4em;
    margin-bottom: 3px;
    margin-right: 6px;
}

.lyrics {
    text-align: left;
    font-weight: bold;
    white-space: nowrap;
}

@media (max-width: 600px) {
    .chord-sheet {
        font-size: 0.6rem;
    }
    .chord {
        font-size: 0.8rem;
    }
}
```

**Comment by erzonmr** [comment]
thank you very much, I will try it

**Comment by erzonmr** [comment]
Hi @soondor81, I'm using it and you see words stuck together.... :-(

**Comment by soondor81** [comment]
@erzonmr 
If necessary, add margin to the .column appropriately.
```css
.column {
    ...
    margin-right: 6px;
}
```
