### ISSUE TITLE
Isolated CSS environment via Shadow DOM (generally, web components)

### ISSUE THREAD

**Issue by patarapolw** [martijnversluis/ChordSheetJS#213]
This will make CSS formatting easier, and not interfered from the outside.

A suggested CSS is

```less
  .chord-sheet {
    .row {
      display: flex;
      flex-direction: row;
    }

    .column {
      display: flex;
      flex-direction: column;
      height: 100%;
    }

    .chord, .lyrics {
      flex-grow: 1;

      &::before {
        content: '\200b';
      }

      * + & {
        margin-left: 0.5em;
      }
    }
  }
```

**Comment by martijnversluis** [comment]
Hi @patarapolw,

Thanks for your suggestion. I don't have much experience with shadow DOM/web components, how would that change the working of the CSS you suggested?

There is a generic item for this on the task board, you can follow that one to be updated on the progress: https://github.com/martijnversluis/ChordSheetJS/issues/184

**Comment by patarapolw** [comment]
As I said, it would absolutely prevent interfere with global CSS.

Although, an alternative solution, is to use a non-generic CSS selector.

```scss
  [data-chordsheetjs] {
    .row {
      display: flex;
      flex-direction: row;
    }

    .column {
      display: flex;
      flex-direction: column;
      height: 100%;
    }

    .chord, .lyrics {
      flex-grow: 1;

      &amp;::before {
        content: '\200b';
      }

      * + &amp; {
        margin-left: 0.5em;
      }
    }
  }
```
